### ISSUE TITLE
suggestions for how-to-contribute.rst

### ISSUE THREAD

**Issue by epogrebnyak** [gboehl/macro_puzzles#6]
I'm considering submitting several macro puzzles, but two ideas on your [how to contribute message](https://github.com/gboehl/macro_puzzles/blob/master/how-to-contribute.rst):

> select the file you want to edit (for example the list), and click the small edit button (the pen). Just click the green 'propose file change' button at the bottom when you are finished.

Good suggestion for novice users, but sounds a bit confusing for standard Github workflow. Maybe add something like: _"If you are experienced Github user, you can also fork this repo and submit a pull request (PR) with proposed additions. Please keep one puzzle per per pull request."_

(The green button sounds confusing to me, but I understand making a PR. )

Example of more formalised contributing guidelines (bigger list though):
<https://github.com/binhnguyennus/awesome-scalability/blob/master/CONTRIBUTING.md>

> (citation where puzzle is first mentioned as 'authors', 'year', 'journal')

Ideally you want a first mention and a journal, but sometimes a puzzle becomes a textbook example, maybe allow such contribution too.

**Comment by gboehl** [comment]
Thanks @epogrebnyak ! Good comment, I edited the file in #. Looking forward to your submission!
